### ISSUE TITLE
Could not find "client" in the context or passed in as an option. 

### ISSUE THREAD

**Issue by webberwang** [adamsoffer/next-apollo-example#13]
Issue with example

<img width="862" alt="localhost_3000" src="https://user-images.githubusercontent.com/26264925/62987314-03818300-bdf4-11e9-87e8-23d42f01061f.png">

**Comment by webberwang** [comment]
@adamsoffer This is codesandbox building a fresh copy of the repo 
https://codesandbox.io/s/github/adamsoffer/next-apollo-example

**Comment by adamsoffer** [comment]
I can reproduce in codestandbox, but not when I just clone the repo and run it. Does it work if you just clone the repo (not using codestandbox)?

**Comment by adamsoffer** [comment]
Codestandbox is probably using the develop branch which I no longer use and is out date

**Comment by webberwang** [comment]
@adamsoffer interesting, it works only with `npm` & not `yarn

**Comment by adamsoffer** [comment]
oh yeah, that's strange!

**Comment by niallobrien80** [comment]
I'm also having this issue.

**Comment by adamsoffer** [comment]
Yeah, I'm able to reproduce as well when using. I'll look into this.

**Comment by adamsoffer** [comment]
@niallobrien80 @webberwang this was just fixed by a PR if you want to give it another shot. https://github.com/adamsoffer/next-apollo/pull/52
